apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: grayscale
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"       # au moins 0 pod prêt
        autoscaling.knative.dev/maxScale: "1000"    # jusqu'à 1000 pods pour le burst
        autoscaling.knative.dev/target: "5"         # 1 requête par pod pour forcer scale-up
    spec:
      containers:
        - image: sandjong/grayscale:latest
          name: grayscale
      schedulerName: my-scheduler
      
